### ISSUE TITLE
Details on how to use example

### ISSUE THREAD

**Issue by fmahnke** [jamie-pate/jstruct#18]
Could you give some details on how to make the example work? It seems the user must use `jstruct_parse.py` to generate a header. I tried to do that (using the contents of the example in the README) and get an error.

```
./jstruct_parse.py ../example/main_jstruct.jstruct.h
Traceback (most recent call last):
  File "./jstruct_parse.py", line 191, in <module>
    args.define
  File "./jstruct_parse.py", line 124, in parse_and_generate
    ast, text = parse_jstruct(filename, include_paths=include_paths, defines=defines)
  File "./jstruct_parse.py", line 64, in parse_jstruct
    raise plyparser.ParseError(message)
pycparser.plyparser.ParseError: ../example/main_jstruct.jstruct.h:10:5: before: uint64_t
```

**Comment by arfoll** [comment]
So I've been trying to see if this does what I want - and I came up with this example https://github.com/arfoll/jstruct-example. @jamie-pate any chance you could take a look and tell me how far off I am, is what I am doing completely crazy and why do I need to set JSON_OBJECT_H? Why can't I just use the header normally?

I'm really happy to try and improve the front page doc, but would need a little guidance to try understand how this rather magical lib works :)

**Comment by jamie-pate** [comment]
@fmahnke sorry about not getting back to you. always so busy!

@arfoll you don't need to use `JSON_OBJECT_H`. In your consumer code you can just `#include <json-c/json_object.h>`, or wherever it gets installed.
The lib (including examples/tests) does it this way because it may be used in environments where that header is somewhere other than `<json-c/json_object.h>`.

I was able to generate `data/test.h` and `data/test.init.c` by adding the jstruct dir to the command line:

```
~/git/jstruct/parse/jstruct_parse.py data/test.jstruct.h ~/git/jstruct/util/fake_libc_include ~/git/jstruct/
Success: data/test.h and data/test.init.c generated successfully.
```

`data/test.h`
```
#ifndef TEST_H
#define TEST_H
// Generated automatically by libjstruct. Do Not Modify.

#include <jstruct/jstruct.h>
#include <json-c/json_object.h>
#include <stdint.h>
#include <stdbool.h>
#include <jstruct/error.h>
struct my_json_data
{
  uint64_t id;
  int _id;
  enum jstruct_error err;
  bool active;
  double ratio_double;
  char *name;
  unsigned long long ull;
  char **tags;
  bool ratio_double__null__;
  int tags__length__;
};
extern struct jstruct_object_property my_json_data__jstruct_properties__[];
struct my_json_basic_container
{
  struct my_json_data main_data;
};
extern struct jstruct_object_property my_json_basic_container__jstruct_properties__[];
struct my_json_container
{
  struct my_json_data main_data;
  struct my_json_data array_data[5];
  struct my_json_data *alloc_array_data;
  int alloc_array_data__length__;
};
extern struct jstruct_object_property my_json_container__jstruct_properties__[];

#endif
```

`data/test.init.c`
```
// Generated automatically by libjstruct. Do Not Modify.
#include "test.h"
#include <jstruct/jstruct.h>
#include <json-c/json_object.h>
#include <stdint.h>
#include <stdbool.h>
#include <jstruct/error.h>
struct jstruct_object_property my_json_data__jstruct_properties__[] = {{.name = "id", .schema = "{\n        \"title\": \"Identifier\",\n        \"description\": \"unique object id\",\n        \"type\": \"int\"\n    }", .type = {.json = json_type_int, .extra = jstruct_extra_type_uint64_t}, .offset = offsetof(struct my_json_data, id)}, {.name = "err", .type = {.json = json_type_int, .extra = jstruct_enum_extra_type(enum jstruct_error)}, .offset = offsetof(struct my_json_data, err)}, {.name = "active", .type = {.json = json_type_boolean}, .offset = offsetof(struct my_json_data, active)}, {.nullable = 1, .name = "ratio", .type = {.json = json_type_double}, .offset = offsetof(struct my_json_data, ratio_double), .null_offset = offsetof(struct my_json_data, ratio_double__null__)}, {.name = "other_name", .type = {.json = json_type_string}, .offset = offsetof(struct my_json_data, name)}, {.name = "ull", .type = {.json = json_type_int, .extra = jstruct_extra_type_unsigned_long_long}, .offset = offsetof(struct my_json_data, ull)}, {.name = "tags", .type = {.member = json_type_string, .json = json_type_array}, .offset = offsetof(struct my_json_data, tags), .length_offset = offsetof(struct my_json_data, tags__length__), .dereference = 1, .stride = sizeof(char *)}, {0}};
struct jstruct_object_property my_json_basic_container__jstruct_properties__[] = {{.name = "main_data", .type = {.json = json_type_object, .jstruct = my_json_data__jstruct_properties__}, .offset = offsetof(struct my_json_basic_container, main_data)}, {0}};
struct jstruct_object_property my_json_container__jstruct_properties__[] = {{.name = "main_data", .type = {.json = json_type_object, .jstruct = my_json_data__jstruct_properties__}, .offset = offsetof(struct my_json_container, main_data)}, {.name = "array_data", .type = {.member = json_type_object, .json = json_type_array, .jstruct = my_json_data__jstruct_properties__}, .offset = offsetof(struct my_json_container, array_data), .length = 5, .stride = sizeof(struct my_json_data)}, {.name = "alloc_array_data", .type = {.member = json_type_object, .json = json_type_array, .jstruct = my_json_data__jstruct_properties__}, .offset = offsetof(struct my_json_container, alloc_array_data), .length_offset = offsetof(struct my_json_container, alloc_array_data__length__), .dereference = 1, .stride = sizeof(struct my_json_data)}, {0}};
```

The lib works by parsing the c code into an [_Abstract Syntax Tree_](https://en.wikipedia.org/wiki/Abstract_syntax_tree) (AST), then manipulating/generating the AST to augment your structure definition to contain _metadata_ which can be used to automatically loop through all the fields in the array, and insert/retrieve the values to/from a JSON object. The AST parsing is done in python with ply/[pycparser](https://github.com/eliben/pycparser), but could be ported to a lower level later. (e.g. with c, Lex and Yacc)

The project is an experiment to replace the procedural patterns used to write REST API endpoints in c with declarative patterns. I modeled it after the JSON annotations found in GO. It seems to me like a novel approach in c, as I couldn't find any similar solutions during my research. Most _nice_ JSON implementations bind to higher level languages (E.G. JavaScript, GO). Bindings to c, like `json-c` are extremely procedural and bulky to use.

The idea is that, instead of calling functions which fill a JSON object procedurally, you could annotate a native c structure, place all the values into the structure with normal (much more readable) c code, and use one function call (a macro really) to export your data to JSON (or import your data from json).

The C code itself uses lots of *stupid macro tricks* to generate short, easy to use macros for importing/exporting different JSON types. (see [export_private.h](https://github.com/jamie-pate/jstruct/blob/master/jstruct/export_private.h) ) [export.c](https://github.com/jamie-pate/jstruct/blob/master/jstruct/export.c)

**Comment by jamie-pate** [comment]
PS: it took me a few tries to figure out the issue, but all the options for `jstruct_parse.py` are in the `--help` command:
`~/src/jstruct/parse/jstruct_parse.py --help`
```usage: jstruct_parse.py [-h] [-o OUTFILE] [-i INITFILE] [-s] [-D DEFINE]
                        jstruct_header_filename [includedir [includedir ...]]

Parse x.jstruct.h file and generate x.h and x.init.h

positional arguments:
  jstruct_header_filename
                        x.jstruct.h file to be parsed
  includedir            override/extra directories to pass to the c
                        preprocessor with -I. (Suggested:
                        util/fake_libc_include)


optional arguments:
  -h, --help            show this help message and exit
  -o OUTFILE, --out OUTFILE
                        output header file name. (python re.sub() repl syntax)
  -i INITFILE, --init INITFILE
                        initializer code file name. (python re.sub() repl
                        syntax)
  -s, --silent          silent mode
  -D DEFINE, --define DEFINE
```

**Comment by jamie-pate** [comment]
@fmahnke It looks like you were missing the `includedir` for `util/fake_libc_include` in your command line. (it defines/fakes libc types/functions etc, so that we don't have to parse all of the libc headers to generate the AST)
